using System.Windows.Input;
using Cadroue.Infrastructure;

namespace Cadroue.UIVeneer.PHouse;

public static class PShortcut
{
    private static readonly IReadOnlyDictionary<Key, string> PShortcutKeyNames = new Dictionary<Key, string>
    {
        [Key.A] = "A",
        [Key.B] = "B",
        [Key.C] = "C",
        [Key.D] = "D",
        [Key.E] = "E",
        [Key.F] = "F",
        [Key.G] = "G",
        [Key.H] = "H",
        [Key.I] = "I",
        [Key.J] = "J",
        [Key.K] = "K",
        [Key.L] = "L",
        [Key.M] = "M",
        [Key.N] = "N",
        [Key.O] = "O",
        [Key.P] = "P",
        [Key.Q] = "Q",
        [Key.R] = "R",
        [Key.S] = "S",
        [Key.T] = "T",
        [Key.U] = "U",
        [Key.V] = "V",
        [Key.W] = "W",
        [Key.X] = "X",
        [Key.Y] = "Y",
        [Key.Z] = "Z",
        [Key.D0] = "0",
        [Key.D1] = "1",
        [Key.D2] = "2",
        [Key.D3] = "3",
        [Key.D4] = "4",
        [Key.D5] = "5",
        [Key.D6] = "6",
        [Key.D7] = "7",
        [Key.D8] = "8",
        [Key.D9] = "9",
        [Key.F1] = "F1",
        [Key.F2] = "F2",
        [Key.F3] = "F3",
        [Key.F4] = "F4",
        [Key.F5] = "F5",
        [Key.F6] = "F6",
        [Key.F7] = "F7",
        [Key.F8] = "F8",
        [Key.F9] = "F9",
        [Key.F10] = "F10",
        [Key.F11] = "F11",
        [Key.F12] = "F12",
        [Key.F13] = "F13",
        [Key.F14] = "F14",
        [Key.F15] = "F15",
        [Key.F16] = "F16",
        [Key.F17] = "F17",
        [Key.F18] = "F18",
        [Key.F19] = "F19",
        [Key.F20] = "F20",
        [Key.F21] = "F21",
        [Key.F22] = "F22",
        [Key.F23] = "F23",
        [Key.F24] = "F24",
        [Key.NumPad0] = "Num0",
        [Key.NumPad1] = "Num1",
        [Key.NumPad2] = "Num2",
        [Key.NumPad3] = "Num3",
        [Key.NumPad4] = "Num4",
        [Key.NumPad5] = "Num5",
        [Key.NumPad6] = "Num6",
        [Key.NumPad7] = "Num7",
        [Key.NumPad8] = "Num8",
        [Key.NumPad9] = "Num9",
        [Key.Space] = "Space",
        [Key.Tab] = "Tab",
        [Key.Back] = "Backspace",
        [Key.Delete] = "Delete",
        [Key.Insert] = "Insert",
        [Key.Home] = "Home",
        [Key.End] = "End",
        [Key.PageUp] = "PageUp",
        [Key.PageDown] = "PageDown",
        [Key.Left] = "Left",
        [Key.Right] = "Right",
        [Key.Up] = "Up",
        [Key.Down] = "Down",
        [Key.OemQuestion] = "/",
        [Key.Divide] = "/",
        [Key.OemComma] = ",",
        [Key.OemPeriod] = ".",
        [Key.OemMinus] = "-",
        [Key.Subtract] = "-",
        [Key.OemPlus] = "+",
        [Key.Add] = "+",
        [Key.Multiply] = "Num*",
        [Key.Decimal] = "Num.",
        [Key.OemTilde] = "`",
        [Key.OemOpenBrackets] = "[",
        [Key.OemCloseBrackets] = "]",
        [Key.OemPipe] = "\\",
        [Key.OemBackslash] = "\\",
        [Key.OemSemicolon] = ";",
        [Key.OemQuotes] = "'",
    };

    public static string PShortcutGestureFormat(Key pShortcutKey, ModifierKeys pShortcutModifiers) =>
        LBinding.LBindingGestureFormat(
            PShortcutKeyFormat(pShortcutKey),
            pShortcutModifiers.HasFlag(ModifierKeys.Control),
            pShortcutModifiers.HasFlag(ModifierKeys.Alt),
            pShortcutModifiers.HasFlag(ModifierKeys.Shift),
            pShortcutModifiers.HasFlag(ModifierKeys.Windows));

    public static string PShortcutKeyFormat(Key pShortcutKey) =>
        PShortcutKeyNames.GetValueOrDefault(pShortcutKey, string.Empty);
}
