<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>Cadroue</AssemblyName>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <RuntimeIdentifiers>win-x64;win-arm64</RuntimeIdentifiers>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationIcon>PAssets\PProgram\PProgramIcon.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Cadroue.Core\Cadroue.Core.csproj" />
    <ProjectReference Include="..\Cadroue.ShellEngine\Cadroue.ShellEngine.csproj" />
    <ProjectReference Include="..\Cadroue.Media\Cadroue.Media.csproj" />
    <ProjectReference Include="..\Cadroue.Infrastructure\Cadroue.Infrastructure.csproj" />
    <ProjectReference Include="..\Cadroue.Application\Cadroue.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\THIRD-PARTY-NOTICES.md" Link="THIRD-PARTY-NOTICES.md">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\LICENSE" Link="LICENSE.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="PAssets\PTabs\*.svg" />
    <Resource Include="PAssets\PCompass\*.svg" />
    <Resource Include="PAssets\PPanels\*.svg" />
    <Resource Include="PAssets\PMenus\*.svg" />
    <Resource Include="PAssets\PProgram\*.png" />
    <Resource Include="PAssets\PProgram\*.ico" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\..\localization\*.json" Link="localization\%(Filename)%(Extension)" LogicalName="localization.%(Filename)%(Extension)" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Flyleaf.FFmpeg.Bindings" Version="8.1.0" />
    <PackageReference Include="FlyleafLib" Version="3.10.4" />
    <PackageReference Include="FlyleafLib.Controls.WPF" Version="1.6.4" />
    <PackageReference Include="SharpVectors.Wpf" Version="1.8.5" />
  </ItemGroup>

  <Target Name="ExcludeFlyleafFromSingleFile" BeforeTargets="_ComputeFilesToBundle">
    <ItemGroup>
      <ResolvedFileToPublish Update="@(ResolvedFileToPublish)" Condition="$([System.String]::Copy('%(FileName)').StartsWith('Flyleaf'))">
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
        <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      </ResolvedFileToPublish>
    </ItemGroup>
  </Target>
</Project>
