namespace Cadroue.Core;

public sealed record LWorkOutput(
    string LWorkOutputNamePattern,
    string LWorkOutputContainer,
    string LWorkOutputExtension,
    string LWorkOutputLocation,
    string LWorkOutputLocationFolder,
    string LWorkOutputExportMode,
    string LWorkOutputVideoStream,
    string LWorkOutputVideoMode,
    string LWorkOutputVideoEncoder,
    string LWorkOutputRateControl,
    string LWorkOutputQuality,
    string LWorkOutputSpeedPreset,
    string LWorkOutputVideoSize,
    string LWorkOutputVideoFps,
    string LWorkOutputPixelFormat,
    IReadOnlyDictionary<string, string> LWorkOutputVideoExtras,
    string LWorkOutputAudioStream,
    string LWorkOutputAudioMode,
    string LWorkOutputAudioEncoder,
    string LWorkOutputAudioBitrate,
    string LWorkOutputAudioSampleRate,
    string LWorkOutputAudioChannels);
