<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Cadroue.Core\Cadroue.Core.csproj" />
    <ProjectReference Include="..\Cadroue.Application\Cadroue.Application.csproj" />
    <ProjectReference Include="..\Cadroue.Media\Cadroue.Media.csproj" />
    <ProjectReference Include="..\Cadroue.Infrastructure\Cadroue.Infrastructure.csproj" />
  </ItemGroup>
</Project>
